services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: ggs_back
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      - ConnectionStrings__Default=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - back_net
      - db_net

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: ggs_front
    depends_on:
      - back
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - back_net

  db:
    image: postgres:18
    container_name: ggs_db
    ports:
      - "5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql
    env_file:
      - .env
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      device: ./data/postgresql
      o: bind

networks:
  back_net:
    name: back_net
    driver: bridge
  db_net:
    name: db_net
    driver: bridge
