services:
  back:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./back:/app
      - ./certs:/certs

  front:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
      - /app/node_modules
      - ./certs:/certs
