services:
  back:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./back:/app
      - ./certs:/certs

  front:
    volumes:
      - ./front:/app
