// <auto-generated />
using System;
using Ggs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ggs.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505132551_GameLibraryRefactor")]
    partial class GameLibraryRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameUser", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("LibraryId", "LibraryUsersId");

                    b.HasIndex("LibraryUsersId");

                    b.ToTable("UserGame", (string)null);
                });

            modelBuilder.Entity("Ggs.Domain.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedById");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Ggs.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.HasOne("Ggs.Domain.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ggs.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LibraryUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ggs.Domain.Models.Game", b =>
                {
                    b.HasOne("Ggs.Domain.Models.User", "SubmittedBy")
                        .WithMany("SubmittedGames")
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Ggs.Domain.Models.User", b =>
                {
                    b.Navigation("SubmittedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
