server {
    listen 443 ssl;

    ssl_certificate /certs/cert.pem;
    ssl_certificate_key /certs/cert-key.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
